### ISSUE TITLE
Access Key ID should be returned as username, not IAM username

### ISSUE THREAD

**Issue by ruthwells** [pepperize/cdk-ses-smtp-credentials#219]
https://github.com/pepperize/cdk-ses-smtp-credentials/blob/6a1f0d467663d37f009d730883f366ff341c8952/src/provider/credentials-handler.lambda.ts#L39

Should this be instead: 
```
          [Credentials.USERNAME]: accessKeyId,
```
This is consistent with the docs (and what is required for email verification to work):
```
// smtpCredentials.secret contains json value {username: "<the generated access key id>", password: "<the calculated ses smtp password>"}
```
To replicate, create a new IAM user and instance of `SesSmtpCredentials` referencing that user, and examine the secret generated in AWS Secrets Manager.

**Comment by pflorek** [comment]
@ruthwells Thank you for the report 😉
